version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env  # Ensure the .env file is loaded
    networks:
      - app-network

networks:
  app-network:
    driver: bridge